# Site settings
title: Texas LLC Formation - Best Value Guaranteed
email: jleak@josephleaklaw.com
description: > # this means to ignore newlines until "baseurl:"
  Get a Texas LLC filed same day for the most affordable price. We provide only one option, everything you need and nothing you don't.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://texasllcform.com" # the base hostname & protocol for your site
twitter_username: csakon
github_username:  csakon

# Build settings
markdown: kramdown
